language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

cache: pip

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"

script:
  - flake8 pyfoobot
  - pylint pyfoobot
  - pydocstyle pyfoobot
  - py.test
